import { Product } from '@/types';

// Expanded to 24 products to accommodate pagination testing (e.g. 12 items per page)
export const products: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-fidelity sound with active noise cancellation and 30-hour battery life. Perfect for audiophiles and travelers.",
    price: 349.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    reviewCount: 1250,
  },
  {
    id: "2",
    name: "Minimalist Leather Backpack",
    description: "Handcrafted from full-grain leather. Features a padded laptop sleeve and multiple organizational pockets.",
    price: 185.00,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800",
    rating: 4.9,
    reviewCount: 84,
  },
  {
    id: "3",
    name: "Smart Fitness Watch",
    description: "Track your health metrics, receive notifications, and enjoy specialized workout modes with a gorgeous OLED display.",
    price: 249.50,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800",
    rating: 4.6,
    reviewCount: 342,
  },
  {
    id: "4",
    name: "Organic Cotton T-Shirt",
    description: "The perfect everyday tee. Breathable, ethically sourced organic cotton in a tailored but relaxed fit.",
    price: 35.00,
    category: "Clothing",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800",
    rating: 4.5,
    reviewCount: 520,
  },
  {
    id: "5",
    name: "Ceramic Pour-Over Coffee Maker",
    description: "Brew barista-quality coffee at home. Elegant matte ceramic design with a premium wooden base.",
    price: 48.00,
    category: "Home & Kitchen",
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&q=80&w=800",
    rating: 4.7,
    reviewCount: 215,
  },
  {
    id: "6",
    name: "Noise-Isolating Earbuds",
    description: "Compact true wireless earbuds delivering punchy bass and crystal clear highs. Sweat and water-resistant.",
    price: 129.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800",
    rating: 4.4,
    reviewCount: 430,
  },
  {
    id: "7",
    name: "Classic Aviator Sunglasses",
    description: "Polarized lenses with UV400 protection framed in lightweight, durable alloy.",
    price: 85.00,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    reviewCount: 190,
  },
  {
    id: "8",
    name: "Linen Blend Button-Down",
    description: "A breezy, versatile outer layer perfect for summer evenings and casual office days.",
    price: 65.00,
    category: "Clothing",
    image: "https://images.unsplash.com/photo-1596755094514-f87e32f85e2c?auto=format&fit=crop&q=80&w=800",
    rating: 4.6,
    reviewCount: 112,
  },
  {
    id: "9",
    name: "Mechanical Keycap Set",
    description: "Double-shot PBT keycaps with custom legends. Compatible with most Cherry MX style switches.",
    price: 45.00,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=800",
    rating: 4.3,
    reviewCount: 154,
  },
  {
    id: "10",
    name: "Ergonomic Office Chair",
    description: "Fully adjustable lumbar support, breathable mesh back, and 4D armrests for maximum comfort.",
    price: 299.00,
    category: "Furniture",
    image: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=800",
    rating: 4.7,
    reviewCount: 890,
  },
  {
    id: "11",
    name: "Hydrating Facial Cleanser",
    description: "Gentle, non-foaming formula with hyaluronic acid to restore the skin's natural barrier.",
    price: 18.50,
    category: "Beauty",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    reviewCount: 2045,
  },
  {
    id: "12",
    name: "Stainless Steel Water Bottle",
    description: "Vacuum-insulated double-wall design keeps drinks cold for 24 hours or hot for 12 hours.",
    price: 32.00,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=800",
    rating: 4.9,
    reviewCount: 310,
  },
  {
    id: "13",
    name: "Yoga Mat with Alignment Lines",
    description: "Eco-friendly natural rubber with a non-slip polyurethane top layer and laser-engraved alignment guides.",
    price: 75.00,
    category: "Sports",
    image: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&q=80&w=800",
    rating: 4.5,
    reviewCount: 423,
  },
  {
    id: "14",
    name: "Hand-Poured Soy Candle",
    description: "Notes of amber, sandalwood, and vanilla. 50-hour burn time in a reusable minimalist glass jar.",
    price: 24.00,
    category: "Home & Kitchen",
    image: "https://images.unsplash.com/photo-1602874801007-bd458fc1d317?auto=format&fit=crop&q=80&w=800",
    rating: 4.7,
    reviewCount: 128,
  },
  {
    id: "15",
    name: "Retro Polaroid Camera",
    description: "Capture memories instantly with this modernized classic. Features auto-focus and double exposure mode.",
    price: 119.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&q=80&w=800",
    rating: 4.6,
    reviewCount: 560,
  },
  {
    id: "16",
    name: "Sustainable Denim Jacket",
    description: "Classic fit made from 100% recycled cotton. Finished with low-impact dyes and vintage hardware.",
    price: 98.00,
    category: "Clothing",
    image: "https://images.unsplash.com/photo-1576995810514-68897db67425?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    reviewCount: 215,
  },
  {
    id: "17",
    name: "Cast Iron Skillet",
    description: "Pre-seasoned and ready to use. Exceptional heat retention for searing, baking, and frying.",
    price: 45.00,
    category: "Home & Kitchen",
    image: "https://images.unsplash.com/photo-1584282433083-d5d118dc8a89?auto=format&fit=crop&q=80&w=800",
    rating: 4.9,
    reviewCount: 3400,
  },
  {
    id: "18",
    name: "Running Shoes",
    description: "Lightweight mesh upper with responsive foam cushioning for maximum energy return during your miles.",
    price: 130.00,
    category: "Clothing",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800",
    rating: 4.5,
    reviewCount: 890,
  },
  {
    id: "19",
    name: "Leather Wallet",
    description: "Slim bifold design featuring RFID blocking technology, 6 card slots, and a premium cash pocket.",
    price: 55.00,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800",
    rating: 4.6,
    reviewCount: 412,
  },
  {
    id: "20",
    name: "Vitamin C Serum",
    description: "Brightens and evens skin tone while providing antioxidant protection against environmental stressors.",
    price: 38.00,
    category: "Beauty",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800",
    rating: 4.4,
    reviewCount: 1560,
  },
  {
    id: "21",
    name: "Adjustable Dumbbell Set",
    description: "Space-saving design that replaces 15 sets of weights. Adjusts from 5 to 52.5 lbs in increments.",
    price: 349.00,
    category: "Sports",
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    reviewCount: 670,
  },
  {
    id: "22",
    name: "Standing Desk Converter",
    description: "Easily transition from sitting to standing with a smooth gas-spring height adjustment mechanism.",
    price: 145.00,
    category: "Furniture",
    image: "https://images.unsplash.com/photo-1595514603683-5fcab01e82e4?auto=format&fit=crop&q=80&w=800",
    rating: 4.7,
    reviewCount: 320,
  },
  {
    id: "23",
    name: "Portable Bluetooth Speaker",
    description: "Waterproof, dustproof, and drop-proof. Delivers 360-degree sound with deep bass for up to 15 hours.",
    price: 89.99,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=800",
    rating: 4.6,
    reviewCount: 1120,
  },
  {
    id: "24",
    name: "Knitted Throw Blanket",
    description: "Ultra-soft and cozy chunky knit blanket, perfect for lounging on the sofa on chilly evenings.",
    price: 58.00,
    category: "Home & Kitchen",
    image: "https://images.unsplash.com/photo-1580828326068-1eeaddbd998f?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    reviewCount: 455,
  }
];

export const getCategories = () => {
  const categories = products.map((product) => product.category);
  return ["All", ...Array.from(new Set(categories))];
};
